const images = {
  avatar: require("./avatar.jpg"),
  noImage: require("./no-image.png"),

  logo: {
    light: require("./logo/logo-light.svg").default,
    dark: require("./logo/logo-dark.svg").default,
  },
  icon: {
    zingMP3: require("./icon/icon-zing-mp3.svg").default,
    play: require("./icon/icon-play.svg").default,
    playing: require("./icon/icon-playing.gif"),
  },
  background: {
    zingChart: require("./background/bg-zing-chart.jpg"),
    weekChart: require("./background/bg-week-chart.jpg"),
    emptyAlbumDark: require("./background/empty-album-dark.png"),
    notFound: require("./background/not-found.jpg"),
  },

  artists: {
    chiDan: require("./artists/chi-dan.png"),
    ducPhuc: require("./artists/duc-phuc.png"),
    erik: require("./artists/erik.png"),
    hoaMinzy: require("./artists/hoa-minzy.png"),
    huongLy: require("./artists/huong-ly.png"),
    jack: require("./artists/jack.png"),
    justatee: require("./artists/justatee.png"),
    karik: require("./artists/karik.png"),
    mrSiro: require("./artists/mr-siro.png"),
    onlyC: require("./artists/onlyc.png"),
    trinhThanhBinh: require("./artists/trinh-thanh-binh.png"),
  },

  themeThumb: {
    blueLight: require("./theme-thumb/blue-light.jpg"),
    blue: require("./theme-thumb/blue.jpg"),
    brown: require("./theme-thumb/brown.jpg"),
    dark: require("./theme-thumb/dark.jpg"),
    dynamicBlue: require("./theme-thumb/dynamic-blue.jpg"),
    dynamicBrown: require("./theme-thumb/dynamic-brown.jpg"),
    dynamicLightDark: require("./theme-thumb/dynamic-light-dark-1.jpg"),
    dynamicPink: require("./theme-thumb/dynamic-pink.jpg"),
    eiffel: require("./theme-thumb/eiffel.jpg"),
    gray: require("./theme-thumb/gray.jpg"),
    grayLight: require("./theme-thumb/gray-light.jpg"),
    green: require("./theme-thumb/green.jpg"),
    iu: require("./theme-thumb/iu.jpg"),
    jack: require("./theme-thumb/jack.jpg"),
    jennie: require("./theme-thumb/jennie.jpg"),
    jiChangWook: require("./theme-thumb/ji-chang-wook.jpg"),
    jisoo: require("./theme-thumb/jisoo.jpg"),
    light: require("./theme-thumb/light.jpg"),
    lisa: require("./theme-thumb/lisa.jpg"),
    london: require("./theme-thumb/london.png"),
    pinkLight: require("./theme-thumb/pink-light.jpg"),
    pink: require("./theme-thumb/pink.jpg"),
    purple: require("./theme-thumb/purple.jpg"),
    red: require("./theme-thumb/red.jpg"),
    rose: require("./theme-thumb/rose.jpg"),
    xone: require("./theme-thumb/xone.jpg"),
    zma: require("./theme-thumb/zma.jpg"),
    girl1: require("./theme-thumb/girl1.png"),
    girl2: require("./theme-thumb/girl2.png"),
    girl3: require("./theme-thumb/girl3.png"),
    girl4: require("./theme-thumb/girl4.png"),
  },

  musicKind: {
    kind1: require("./music-kind/kind1.jpg"),
    kind2: require("./music-kind/kind2.jpg"),
    kind3: require("./music-kind/kind3.jpg"),
    kind4: require("./music-kind/kind4.jpg"),
  },
};

export default images;
